name: Deploy to AWS EC2 via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files to EC2 via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: "."
        target: "/home/ubuntu/app-lks"
        strip_components: 1

    - name: Executing remote SSH commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/app-lks
          
          echo "=== BERHENTIKAN KONTAINER LAMA (JIKA ADA) ==="
          sudo docker stop lks-container || true
          sudo docker rm lks-container || true
          
          echo "=== MEMULAI BUILD IMAGE BARU DI EC2 ==="
          sudo docker build -t lks-app-ec2:latest .
          
          echo "=== JALANKAN KONTAINER BARU ==="
          sudo docker run -d --name lks-container -p 8080:8080 lks-app-ec2:latest
          
          echo "=== DEPLOY SELESAI DAN BERHASIL ==="
          sudo docker ps
